packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@heroicons/react": ^2.2.0
  "@heroui/react": ^3.0.2
  "@heroui/styles": ^3.0.2
  "@tailwindcss/vite": ^4.2.2
  "@types/node": ^24
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^6.0.1
  get-port: ^7.2.0
  i18next: ^26.0.3
  i18next-browser-languagedetector: ^8.2.1
  i18next-cli: ^1.51.6
  i18next-http-backend: ^3.0.4
  react: ^19.2.4
  react-dom: ^19.2.4
  react-grab: ^0.1.29
  react-i18next: ^17.0.2
  tailwindcss: ^4.2.2
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  wouter: ^3.9.0
  zustand: ^5.0.12

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
